---
- name: Ensure jenkins is installed
  yum:
     name: jenkins-{{jenkins_version_redhat}}
     state: present
  notify:
    - jenkins started

- name: Ensure required plugins are installed
  jenkins_plugin:
     name: "{{item}}"
     state: latest
     params: "{{ my_jenkins_params }}"
     url_password: admin
     updates_url: https://updates.jenkins-ci.org
     url: http://localhost:8080
     with_dependencies: yes
  with_items: "{{ my_jenkins_plugins }}"
  notify:
    - restart jenkins
  tags:
    - plugins

- name: Ensure jenkins server is up and running
  wait_for:
      host: localhost
      port: "{{jenkins_port}}"
      delay: 10

- name: Ensure jenkins_jobs module dependencies are installed
  yum:
    name: "{{item}}"
    state: present
  with_items:
       - python-jenkins
       - python-lxml

- name: Ensure Sample-jobs are created
  jenkins_job:
     name: "{{item}}"
     state: present
     config: "{{ lookup('file', 'templates/{{item}}_config.xml') }}"
    # enabled: False  (mutually exclusive with config attribute)
     user: admin
     password: admin
     url: http://localhost:8080
  with_items: "{{my_jenkins_jobs}}"
  tags:
     - jobs
