---

- name: Ensure required plugins are installed
  jenkins_plugin:
     name: "{{item}}"
     state: latest
     params: "{{ my_jenkins_params }}"
     url_password: admin
     updates_url: https://updates.jenkins-ci.org
     url: http://localhost:8080
     with_dependencies: yes
  with_items: "{{ my_jenkins_plugins }}"


- name: Ensure jenkins_jobs module dpendencies are installed
  yum:
    name: "{{item}}"
    state: present
  with_items:
       - python-jenkins
       - python-lxml

- name: Ensure Sampljobs are created
  jenkins_job:
     name: sample-job1
     state: present
     config: "{{ lookup('file', 'templates/sample-job1_config.xml') }}"
    # enabled: False  (mutually exclusive with config attribute)
     user: admin
     password: admin
     url: http://localhost:8080

- name: Ensure Sampljobs are created
  jenkins_job:
     name: sample-job2
     state: present
     config: "{{ lookup('file', 'templates/sample-job2_config.xml') }}"
    # enabled: False  (mutually exclusive with config attribute)
     user: admin
     password: admin
     url: http://localhost:8080
