---
- name: Create new jobs or update existing jobs if there is any change
  copy:
    scr: "files/{{item}}"
    dest: "/tmp/{{item}}"
  with_items:
     - sample-job1_config.xml
     - sample-job2_config.xml
     - jenkins-jobs.sh

- shell: "sh /tmp/jenkins_jobs.sh sample-job1 sample-job2"
