---
- name: Create new jobs or update existing jobs if there is any change
  template:
    src:  files/{{item}}
    dest: /tmp/
    force: yes
  with_items:
     - sample-job1_config.xml
     - sample-job2_config.xml
     - jenkins-jobs.sh
  

- shell: "sh /tmp/jenkins-jobs.sh sample-job1 sample-job2"
