---

- name: Ensure jenkins is installed
  yum:
     name: jenkins-{{jenkins_version_redhat}}
     state: present
  notify:
    - jenkins started
  tags:
    - install


- name: Ensure required plugins are installed
  jenkins_plugin:
     name: "{{item}}"
     state: present
     params: "{{ my_jenkins_params }}"
     url_password: admin
     updates_url: https://updates.jenkins-ci.org
     url: http://localhost:8080
     with_dependencies: yes
  with_items: "{{ my_jenkins_plugins }}"
  environment:
        http_proxy: "{{proxy_http}}"
        https_proxy: "{{proxy_http}}"
        no_proxy: "{{proxy_no}}"
  notify:
    - restart jenkins
  tags:
    - plugins


- name: Ensure jenkins server is up and running
  uri:
      url: "http://localhost:{{jenkins_port}}"
      method: HEAD
      user: admin
      password: admin
      force_basic_auth: yes
      status_code: 200
      timeout: 30
  register: result
  until: result.status == 200
  retries: 10
  delay: 10
  tags:
    - install
    - plugins


- name: Ensure jenkins_jobs module dependencies are installed
  yum:
    name: "{{item}}"
    state: present
  with_items:
       - python-jenkins
       - python-lxml

- name: Ensure Sample-jobs are created
  jenkins_job:
     name: "{{item}}"
     config: "{{ lookup('file', 'templates/{{item}}_config.xml') }}"
    # enabled: False  (mutually exclusive with config attribute)
     user: admin
     password: admin
     url: http://localhost:8080
     state: present
  with_items: "{{my_jenkins_jobs}}"
  tags:
     - jobs
